data_dirs:
  - 'data/folder1'
  - 'data/folder2'
  - 'data/folder3'
  - 'data/folder4'
  - 'data/folder5'

tokenized_datasets_dirs:
  - 'tokenized_datasets_folder1'
  - 'tokenized_datasets_folder2'
  - 'tokenized_datasets_folder3'
  - 'tokenized_datasets_folder4'
  - 'tokenized_datasets_folder5'